# More On Numpy

In [1]:
import numpy as np

In [2]:
arr = np.array([5,1,7,9,3])
arr

array([5, 1, 7, 9, 3])

In [3]:
arr.ndim

1

In [4]:
arr.shape

(5,)

In [10]:
arr = np.array([
    [20,60,-6,45],
    [10,8,6,44],
    [115,82,-66,-344],
    [41,32,-86,-411],
    [15,2,6,-4],
    [1105,802,-660,-3404],
])
arr

array([[   20,    60,    -6,    45],
       [   10,     8,     6,    44],
       [  115,    82,   -66,  -344],
       [   41,    32,   -86,  -411],
       [   15,     2,     6,    -4],
       [ 1105,   802,  -660, -3404]])

In [11]:
arr.ndim

2

In [12]:
arr.shape

(6, 4)

## Slicing

In [13]:
arr

array([[   20,    60,    -6,    45],
       [   10,     8,     6,    44],
       [  115,    82,   -66,  -344],
       [   41,    32,   -86,  -411],
       [   15,     2,     6,    -4],
       [ 1105,   802,  -660, -3404]])

In [15]:
print(arr[3,2])

-86


In [16]:
arr[3,2]

np.int64(-86)

In [17]:
arr

array([[   20,    60,    -6,    45],
       [   10,     8,     6,    44],
       [  115,    82,   -66,  -344],
       [   41,    32,   -86,  -411],
       [   15,     2,     6,    -4],
       [ 1105,   802,  -660, -3404]])

In [18]:
arr[2:4]

array([[ 115,   82,  -66, -344],
       [  41,   32,  -86, -411]])

In [19]:
arr[2:4,1:3]

array([[ 82, -66],
       [ 32, -86]])

In [20]:
arr

array([[   20,    60,    -6,    45],
       [   10,     8,     6,    44],
       [  115,    82,   -66,  -344],
       [   41,    32,   -86,  -411],
       [   15,     2,     6,    -4],
       [ 1105,   802,  -660, -3404]])

In [21]:
arr = np.array([
    [10,20,30],
    [1,2,3],
    [2,4,6]
])
arr

array([[10, 20, 30],
       [ 1,  2,  3],
       [ 2,  4,  6]])

In [22]:
arr.shape


(3, 3)

In [23]:
arr.size

9

In [24]:
arr

array([[10, 20, 30],
       [ 1,  2,  3],
       [ 2,  4,  6]])

In [25]:
arr[0,1] = 4

In [26]:
arr

array([[10,  4, 30],
       [ 1,  2,  3],
       [ 2,  4,  6]])

In [27]:
arr[0,-1] = 2

In [28]:
arr

array([[10,  4,  2],
       [ 1,  2,  3],
       [ 2,  4,  6]])

In [29]:
arr.sum()

np.int64(34)

In [30]:
arr.sum(axis=-1)

array([16,  6, 12])

In [31]:
arr.sum(axis=0)

array([13, 10, 11])

In [32]:
arr.sum(axis=-1)

array([16,  6, 12])

In [33]:
arr.sum(axis=-1).reshape(3,1)

array([[16],
       [ 6],
       [12]])

In [34]:
arr

array([[10,  4,  2],
       [ 1,  2,  3],
       [ 2,  4,  6]])

In [36]:
arr.reshape(9,1)

array([[10],
       [ 4],
       [ 2],
       [ 1],
       [ 2],
       [ 3],
       [ 2],
       [ 4],
       [ 6]])

In [37]:
arr.reshape(9)

array([10,  4,  2,  1,  2,  3,  2,  4,  6])

In [38]:
arr

array([[10,  4,  2],
       [ 1,  2,  3],
       [ 2,  4,  6]])

In [39]:
arr.reshape(4,3)

ValueError: cannot reshape array of size 9 into shape (4,3)

In [41]:
np.zeros(5, dtype="int")

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [44]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
np.zeros((4,5)).reshape(2,10)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [46]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Flat multi dimension array

In [47]:
arr

array([[10,  4,  2],
       [ 1,  2,  3],
       [ 2,  4,  6]])

In [ ]:
# flatten -> returns the copy 

new_arr = arr.flatten()

new_arr

array([10,  4,  2,  1,  2,  3,  2,  4,  6])

In [49]:
arr

array([[10,  4,  2],
       [ 1,  2,  3],
       [ 2,  4,  6]])

In [50]:
new_arr[2] = 25

In [51]:
new_arr

array([10,  4, 25,  1,  2,  3,  2,  4,  6])

In [52]:
arr

array([[10,  4,  2],
       [ 1,  2,  3],
       [ 2,  4,  6]])

In [53]:
## ravel -> whenever possible it will return view or actual array

new_ravel_arr = arr.ravel()

new_ravel_arr

array([10,  4,  2,  1,  2,  3,  2,  4,  6])

In [54]:
arr

array([[10,  4,  2],
       [ 1,  2,  3],
       [ 2,  4,  6]])

In [55]:
new_ravel_arr[-1] = 10

In [56]:
new_ravel_arr

array([10,  4,  2,  1,  2,  3,  2,  4, 10])

In [57]:
arr

array([[10,  4,  2],
       [ 1,  2,  3],
       [ 2,  4, 10]])

In [58]:
arr

array([[10,  4,  2],
       [ 1,  2,  3],
       [ 2,  4, 10]])

In [59]:
arr.min()

np.int64(1)

In [60]:
arr.min(axis=-1)

array([2, 1, 2])

In [61]:
arr.min(axis=0)

array([1, 2, 2])

In [62]:
arr.max()

np.int64(10)

In [64]:
arr.max(axis=-1)

array([10,  3, 10])

In [65]:
# Loop over np arr

In [67]:
for row in arr:
    print(row)

[10  4  2]
[1 2 3]
[ 2  4 10]


In [68]:
for row in arr:
    for data in row:
        print(data)

10
4
2
1
2
3
2
4
10


In [69]:
arr = np.array([81,64,25,30])
arr

array([81, 64, 25, 30])

In [70]:
np.sqrt(arr)

array([9.        , 8.        , 5.        , 5.47722558])

In [71]:
np.std(arr)

np.float64(23.355941428253324)

In [73]:
arr.mean()

np.float64(50.0)

In [74]:
np.std(arr).round(2)

np.float64(23.36)