# More On Numpy

In [1]:
import numpy as np

In [2]:
arr = np.array([5,1,7,9,3])
arr

array([5, 1, 7, 9, 3])

In [3]:
arr.ndim

1

In [4]:
arr.shape

(5,)

In [10]:
arr = np.array([
    [20,60,-6,45],
    [10,8,6,44],
    [115,82,-66,-344],
    [41,32,-86,-411],
    [15,2,6,-4],
    [1105,802,-660,-3404],
])
arr

array([[   20,    60,    -6,    45],
       [   10,     8,     6,    44],
       [  115,    82,   -66,  -344],
       [   41,    32,   -86,  -411],
       [   15,     2,     6,    -4],
       [ 1105,   802,  -660, -3404]])

In [11]:
arr.ndim

2

In [12]:
arr.shape

(6, 4)

## Slicing

In [13]:
arr

array([[   20,    60,    -6,    45],
       [   10,     8,     6,    44],
       [  115,    82,   -66,  -344],
       [   41,    32,   -86,  -411],
       [   15,     2,     6,    -4],
       [ 1105,   802,  -660, -3404]])

In [15]:
print(arr[3,2])

-86


In [16]:
arr[3,2]

np.int64(-86)

In [17]:
arr

array([[   20,    60,    -6,    45],
       [   10,     8,     6,    44],
       [  115,    82,   -66,  -344],
       [   41,    32,   -86,  -411],
       [   15,     2,     6,    -4],
       [ 1105,   802,  -660, -3404]])

In [18]:
arr[2:4]

array([[ 115,   82,  -66, -344],
       [  41,   32,  -86, -411]])

In [19]:
arr[2:4,1:3]

array([[ 82, -66],
       [ 32, -86]])