<h1 style="text-align:center;">Matrix Examples</h1>

<img src="./matrix.png" alt="Matrix Image" width="500px">

![Matrix Image](matrix.png)

In [1]:
import numpy as np

In [2]:
q1_sales = np.array([
    [10,15,6],
    [25,12,18],
    [28,10,5]
])

q1_sales

array([[10, 15,  6],
       [25, 12, 18],
       [28, 10,  5]])

In [13]:
q2_sales = np.array([
    [35,12,8],
    [30,15,14],
    [10,0,5]
])

q2_sales

array([[35, 12,  8],
       [30, 15, 14],
       [10,  0,  5]])

# Total unit sold in both quarters

In [14]:
q1_sales + q2_sales

array([[45, 27, 14],
       [55, 27, 32],
       [38, 10, 10]])

# Sales unit growth from q1 to q2

In [15]:
q2_sales-q1_sales

array([[ 25,  -3,   2],
       [  5,   3,  -4],
       [-18, -10,   0]])

# Percentage growth in sales from q1 to q2

In [16]:
(q2_sales-q1_sales)/q1_sales * 100

array([[ 250.        ,  -20.        ,   33.33333333],
       [  20.        ,   25.        ,  -22.22222222],
       [ -64.28571429, -100.        ,    0.        ]])

# Find Quarter 1 Revenue

In [17]:
prices = np.array([
    [110,105,98],
    [50,48,51],
    [10,8,12]
])

prices

array([[110, 105,  98],
       [ 50,  48,  51],
       [ 10,   8,  12]])

In [18]:
q1_revenue = prices * q1_sales
q1_revenue

array([[1100, 1575,  588],
       [1250,  576,  918],
       [ 280,   80,   60]])

In [19]:
q1_discount = q1_revenue * 0.2
q1_discount


array([[220. , 315. , 117.6],
       [250. , 115.2, 183.6],
       [ 56. ,  16. ,  12. ]])

In [20]:
q1_net_revenue = q1_revenue - q1_discount

In [21]:
q1_net_revenue

array([[ 880. , 1260. ,  470.4],
       [1000. ,  460.8,  734.4],
       [ 224. ,   64. ,   48. ]])

In [22]:
q1_discount.sum()

np.float64(1285.4)

In [23]:
q1_net_revenue.sum()

np.float64(5141.6)

In [ ]:
arr1 = np.array([1,2,3])
arr2=np.array([10,8,7])

np.dot(arr1,arr2)

np.int64(47)

In [25]:
arr1 = np.array([
    [1,2,3],
    [5,4,3],
    [10,1,3]
    ])
arr2=np.array(
    [
        [2,4],
        [6,9],
        [1,2]
    ])

np.dot(arr1,arr2)

array([[17, 28],
       [37, 62],
       [29, 55]])

# Stacking

In [28]:
student = np.array(
[
    [101,"Rohit",25],
    [102,"SHivam",28],
    [103,"Pranjal",29],
    [104,"Rohini",18],
]

)

student_info = np.array([
    [101,"Male",85.5],
    [102,"Male",35.55],
    [104,"Female",98.99],
    [103,"Female",38.99],
])

print(student)
print(student_info)

[['101' 'Rohit' '25']
 ['102' 'SHivam' '28']
 ['103' 'Pranjal' '29']
 ['104' 'Rohini' '18']]
[['101' 'Male' '85.5']
 ['102' 'Male' '35.55']
 ['104' 'Female' '98.99']
 ['103' 'Female' '38.99']]


In [29]:
np.hstack((student,student_info))

array([['101', 'Rohit', '25', '101', 'Male', '85.5'],
       ['102', 'SHivam', '28', '102', 'Male', '35.55'],
       ['103', 'Pranjal', '29', '104', 'Female', '98.99'],
       ['104', 'Rohini', '18', '103', 'Female', '38.99']], dtype='<U32')

In [30]:
more_student = np.array([[105,"Ashish",30],[110,"Shubham",45]])
more_student

array([['105', 'Ashish', '30'],
       ['110', 'Shubham', '45']], dtype='<U21')

In [31]:
np.vstack((student,more_student))

array([['101', 'Rohit', '25'],
       ['102', 'SHivam', '28'],
       ['103', 'Pranjal', '29'],
       ['104', 'Rohini', '18'],
       ['105', 'Ashish', '30'],
       ['110', 'Shubham', '45']], dtype='<U21')