<h1 style="text-align:center;">Matrix Examples</h1>

<img src="./matrix.png" alt="Matrix Image" width="500px">

![Matrix Image](matrix.png)

In [1]:
import numpy as np

In [2]:
q1_sales = np.array([
    [10,15,6],
    [25,12,18],
    [28,10,5]
])

q1_sales

array([[10, 15,  6],
       [25, 12, 18],
       [28, 10,  5]])

In [13]:
q2_sales = np.array([
    [35,12,8],
    [30,15,14],
    [10,0,5]
])

q2_sales

array([[35, 12,  8],
       [30, 15, 14],
       [10,  0,  5]])

# Total unit sold in both quarters

In [14]:
q1_sales + q2_sales

array([[45, 27, 14],
       [55, 27, 32],
       [38, 10, 10]])

# Sales unit growth from q1 to q2

In [15]:
q2_sales-q1_sales

array([[ 25,  -3,   2],
       [  5,   3,  -4],
       [-18, -10,   0]])

# Percentage growth in sales from q1 to q2

In [16]:
(q2_sales-q1_sales)/q1_sales * 100

array([[ 250.        ,  -20.        ,   33.33333333],
       [  20.        ,   25.        ,  -22.22222222],
       [ -64.28571429, -100.        ,    0.        ]])